# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]
lang: ja

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: docs
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: ほりいみほ
description: "【旅×モデル】 旅人として、27ヶ国83都市渡航。 バックパッカー一人旅スタイルが好き。 いつも全力自撮り撮影。 チェコ共和国大使館・チェコ政府観光局主催 チェコ親善アンバサダー2020（2019年に取材旅行参加） 世界遺産学検定2級 モデル歴は8年。 地元奈良を中心にモデル、ショー、観光PR活動もしています。"
keywords: "旅, モデル, 奈良, チェコ共和国, チェコ政府観光局主催 チェコ親善アンバサダー, 旅×モデル"
url: http://horiimiho.jp/
baseurl: ""
siteurl: "https://horiimiho.jp"

google_analytics: 
# repo: http://github.com/hori/end2end
# disqus_shortname: "nandothemes"
# disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: ほりいみほ
  job: 旅モデル
  bio: "【旅×モデル】 旅人として、27ヶ国83都市渡航。 バックパッカー一人旅スタイルが好き。 いつも全力自撮り撮影。 チェコ共和国大使館・チェコ政府観光局主催 チェコ親善アンバサダー2020（2019年に取材旅行参加） 世界遺産学検定2級 モデル歴は8年。 地元奈良を中心にモデル、ショー、観光PR活動もしています。"
  thumb: /images/author.jpg
  #email: nandomoreira.me@gmail.com
  url: http://horiimiho.jp/
  # github: https://github.com/horiimiho29
  twitter: https://twitter.com/horiimiho29
  instagram: https://instagram.com/horiimiho29
  facebook: https://facebook.com/horiimiho29
  # linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: contact
    title: Contact

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
